# Generated by Django 4.1.5 on 2023-05-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='DOB',
        ),
    ]
